app/Http/routes.php
<?php

use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/** ------------------------------------------
 *  Route model binding
*  ------------------------------------------
*/
//Route::model('user', 'User');
Route::model('comment', 'Comment');
Route::model('post', 'Post');
Route::model('role', 'Role');

/** ------------------------------------------
 *  Route constraint patterns
 *  ------------------------------------------
*/
Route::pattern('comment', '[0-9]+');
Route::pattern('post', '[0-9]+');
Route::pattern('page', '[0-9]+');
Route::pattern('user', '[0-9]+');
Route::pattern('photo_id', '[0-9]+');
Route::pattern('role', '[0-9]+');
Route::pattern('token', '[0-9a-z]+');
Route::pattern('post_name', '[0-9a-z]+');
/** ------------------------------------------
 *  Admin Routes
 *  ------------------------------------------
*/
Route::group(array('prefix' => 'admin', 'before' => 'auth'), function()
{

	# Comment Management
	Route::get('comments/{comment}/edit', 'AdminCommentsController@getEdit');
	Route::post('comments/{comment}/edit', 'AdminCommentsController@postEdit');
	Route::get('comments/{comment}/delete', 'AdminCommentsController@getDelete');
	Route::post('comments/{comment}/delete', 'AdminCommentsController@postDelete');
	Route::controller('comments', 'AdminCommentsController');

	# Blog Management
	Route::get('blogs/{post}/show', 'AdminBlogsController@getShow');
	Route::get('blogs/{post}/edit', 'AdminBlogsController@getEdit');
	Route::post('blogs/{post}/edit', 'AdminBlogsController@postEdit');
	Route::get('blogs/{post}/delete', 'AdminBlogsController@getDelete');
	Route::post('blogs/{post}/delete', 'AdminBlogsController@postDelete');
	Route::controller('blogs', 'AdminBlogsController');

	# User Management
	Route::get('users/{user}/show', 'AdminUsersController@getShow');
	Route::get('users/{user}/edit', 'AdminUsersController@getEdit');
	Route::post('users/{user}/edit', 'AdminUsersController@postEdit');
	Route::get('users/{user}/delete', 'AdminUsersController@getDelete');
	Route::post('users/{user}/delete', 'AdminUsersController@postDelete');
	Route::controller('users', 'AdminUsersController');

	# User Role Management
	Route::get('roles/{role}/show', 'AdminRolesController@getShow');
	Route::get('roles/{role}/edit', 'AdminRolesController@getEdit');
	Route::post('roles/{role}/edit', 'AdminRolesController@postEdit');
	Route::get('roles/{role}/delete', 'AdminRolesController@getDelete');
	Route::post('roles/{role}/delete', 'AdminRolesController@postDelete');
	Route::controller('roles', 'AdminRolesController');

	# Admin Dashboard
	Route::controller('/', 'AdminDashboardController');
});


/** ------------------------------------------
 *  Frontend Routes
 *  ------------------------------------------
*/

// User reset routes
Route::get('user/reset/{token}', 'UserController@getReset');
// User password reset
Route::post('user/reset/{token}', 'UserController@postReset');
//:: User Account Routes ::
Route::get('user/{user}', 'UserController@getIndex');
Route::get('user/{user}/edit', 'UserController@getEdit');
Route::post('user/{user}/edit', 'UserController@postEdit');
Route::post('user/login', 'UserController@postLogin');
# User RESTful Routes (Login, Logout, Register, etc)
Route::controller('user', 'UserController');

//:: Application Routes ::

# Filter for detect language
Route::when('contact-us','detectLang');

# Contact Us Static Page
Route::get('contact-us', function()
{
	// Return about us page
	return View::make('site/contact-us');
});

# Posts - Second to last set, match slug
// Route::get('{postSlug}', 'BlogController@getView');
// Route::post('{postSlug}', 'BlogController@postView');

Route::controller('gallery', 'GalleryController');
Route::controller('blog', 'BlogController');
Route::get('blog/view/{post}/{post_name}', 'BlogController@getView');
Route::get('photo/view/{photo_id}', 'PhotoController@getView');
Route::controller('photo', 'PhotoController');
Route::controller('about', 'AboutController');

Route::group(array('prefix'=>'dashboard'), function() {
    Route::get('users/add', 'DashboardController@getUsersAdd');
    Route::get('posts/add', 'DashboardController@getPostsAdd');
    Route::controller('/', 'DashboardController');
});

# Index Page - Last route, no matches
Route::get('page/{page}', 'HomeController@getIndex');
Route::get('/', array('before' => 'detectLang','uses' => 'HomeController@getIndex'));
//Route::get('/', array('before' => 'detectLang','uses' => 'PortfolioController@getIndex'));

Event::listen('illuminate.query', function($query, $params) {
    $debug = Input::get('debug');
    if(Config::get('app.debug') == '1' && $debug === 'true') {
        echo '<pre>';
        var_dump($query);
        var_dump($params);
        echo '</pre>';
    }
});

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

//Route::get('/', 'WelcomeController@index');

// Route::controllers([
// 	'auth' => 'Auth\AuthController',
// 	'password' => 'Auth\PasswordController',
// ]);

app/Models/Flickr.php
<?php

namespace JPAPhotography\Models;

use Illuminate\Database\Eloquent\Model;

class Flickr extends Model {
    protected $table = 'flickr_images';
    public $timestamps = true;
    
    public function getDateUploadAttribute($value) {
        return date('D M d, Y g:i A', $value);
    }
    
    public function getDateTakenAttribute($value) {
        return date_format(date_create($value), 'D M d, Y');
    }
    
    public function getImages() {
        return $this->all();
    }
}

resources/views/site/portfolio/flickr.blade.php
@extends('site.' . config('app.layout') . '.default')

@section('title')
Portfolio :: @parent
@stop

@section('inline_scripts')
$('#carousel-modal').on('open.zf.reveal', function() {
  $('.orbit-container').css({'height': '100em', 'max-height': '100%'});
});
@stop

@section('styles')
.img-wrapper {
    position: relative;
}

.img-wrapper a {
    /*display: block;*/
    position: relative;
    overflow: hidden;
}

.img-wrapper:hover .title {
    opacity: 1;
}

.img-wrapper .title {
    position: absolute;
    overflow: hidden;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background: #333;
    opacity: 0;
    padding: 1.5rem;
    color: #fff;
    background-color: rgba(0, 0, 0, 0.4);
}
.item-wrapper:hover .img-wrapper .title {
    bottom: 8px;
}
.pagination li{
  border: 1px solid #cacaca;
  border-radius: 50%;
  padding: 0;
}
.pagination .current, .pagination .disabled  {
    padding: 0;
}
.pagination span {
    padding: 0.1875rem 0.625rem;
    border-radius: 50%;
    display: block;
}
.pagination a {
  border-radius: 50%;
}
@stop

@section('content')
    @if(Request::input('page', 1) == 1)
        <div class="callout primary">
            <div class="row">
            <h2>JPA Photography</h2>
            <p>Sometimes you learn more from your mistakes than you do from your masterpieces. Remember how
               free clouds are. They just lay around in the sky all day long. If you don't like it - change
               it. It's your world. We'll take a little bit of Van Dyke Brown. From all of us here, I want 
               to wish you happy painting and God bless, my friends. There's not a thing in the world wrong
               with washing your brush.</p>
            </div>
        </div>
    @endif
    <div class="gallery">
        <div class="row">
            <ul class="clearing-thumbs row small-up-2 medium-up-3 large-up-4 text-center no-bullet" data-clearing>
                @foreach($posts as $post)
                    <li class="item-wrapper column">
                        <div class="img-wrapper">
                            <a class="thumbnail radius" data-open="carousel-modal" href="#"><!-- {{ $post['url_l'] }} -->
                                <img data-caption="{{ $post['title'] }}"
                                     width="{{ $post['width_q'] }}"
                                     height="{{ $post['height_q'] }}"
                                     src="{{ $post['url_q'] }}" />
                                <div class="title">
                                    <p class="vertical-center">{{ $post['title'] }}</p>
                                </div>
                            </a>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
        <div id="pagination-wrapper" class="row text-center">
            @include('site.layouts.page', ['results' => $posts])
        </div>
        
    </div>
    
    <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
        <ul class="orbit-container">
            <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
            <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
            <li class="is-active orbit-slide">
                <div>
                    <h3 class="text-center">You can also throw some text in here!</h3>
                    <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde harum rem, beatae ipsa consectetur quisquam. Rerum ratione, delectus atque tempore sed, suscipit ullam, beatae distinctio cupiditate ipsam eligendi tempora expedita.</p>
                    <h3 class="text-center">This Orbit slide has chill</h3>
                </div>
            </li>
            <li class="orbit-slide">
                <div>
                    <h3 class="text-center">You can also throw some text in here!</h3>
                    <p class="text-center">Follow the lay of the land. It's most important. This is the fun part Let's put a touch more of the magic here.</p>
                    <h3 class="text-center">This Orbit slide has chill</h3>
                </div>
            </li>
            <li class="orbit-slide">
                <div>
                    <h3 class="text-center">You can also throw some text in here!</h3>
                    <p class="text-center">We don't want to set these clouds on fire. All you have to do is let your imagination go wild. Every day I learn. Every highlight needs it's own personal shadow. There comes a nice little fluffer. We can always carry this a step further. There's really no end to this.</p>
                    <h3 class="text-center">This Orbit slide has chill</h3>
                </div>
            </li>
            <li class="orbit-slide">
                <div>
                    <h3 class="text-center">You can also throw some text in here!</h3>
                    <p class="text-center">You have to make almighty decisions when you're the creator. Even trees need a friend. We all need friends. Just think about these things in your mind - then bring them into your world. If you've been in Alaska less than a year you're a Cheechako.</p>
                    <h3 class="text-center">This Orbit slide has chill</h3>
                </div>
            </li>
        </ul>
        <nav class="orbit-bullets">
            <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
            <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
            <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
            <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
        </nav>
    </div>
    
@stop

resources/views/site/portfolio/gallery.blade.php
@extends('site.' . config('app.layout') . '.default')
{{-- Content --}}
@section('content')

@foreach ($posts as $post)
<!-- div class="col-sm-1" -->
    <div class="col-md-3">
	<h4>
		<strong>{{ $post['title'] }}</strong>
	</h4>
	
		<a href="{{{ $post['url_l'] }}}" class="thumbnail"><img src="{{{ $post['url_q'] }}}" width="{{{ $post['width_q'] }}}" height="{{{ $post['height_q'] }}}" alt="{{ $post['title'] }}"></a>
	</div>
<!-- /div -->
@endforeach
<div style="clear:both;"></div>
<?php echo $posts->render(); ?>
@stop

resources/views/site/portfolio/index-3.blade.php
@extends('site.' . config('app.layout') . '.default')

@section('title')
Portfolio :: @parent
@stop

@section('added_jquery_script')
$('div.reveal').on('open.zf.reveal', function(event){
    $(this).children('h2').click(function(event){
        $(this).children('button').trigger('click');
    });
    $(this).children('div').click(function(event){
        $(this).children('button').trigger('click');
    });
    $(this).children('div').children('img').click(function(event){
        $(this).children('button').trigger('click');
    });
});
$('a.thumbnail').click(function(event){
    event.preventDefault();
    var modalID = $(this).attr('data-toggle');
    var imgSrc = $(this).attr('href');
    $('#' + modalID + ' img').attr('height', 1024);
    $('#' + modalID + ' img').attr('src', "{{ asset('/images/loading.gif') }}");
    $('#' + modalID + ' img').attr('src', imgSrc);
});
@stop

@section('styles')
div[id^="modal-"] {
    width: 100% !important;
    margin-top: 0;
    top: 0 !important;
}

#loading_gif {
    position: absolute;
    left: 50%;
    top: 50%;
}
.img-wrapper {
    position: relative;
}

.img-wrapper a {
    position: relative;
    overflow: hidden;
}

.thumbnail:hover .title {
    opacity: 1;
}

.img-wrapper .title {
    position: absolute;
    overflow: hidden;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background: #333;
    opacity: 0;
    padding: 1.5rem;
    color: #fff;
    background-color: rgba(0, 0, 0, 0.4);
}
.img-wrapper .title em {
    font-size: 0.8rem;
}
.item-wrapper:hover .img-wrapper .title {
    bottom: 8px;
}

.gallery {
  position: relative;
  width: 100%;
  margin-top: -1rem;
  overflow: hidden;
}
  .gallery_background {
    position: absolute;
    top: 0;
    left: -50%;
    width: 200%;
    height: 200%;
    z-index: -1;
    /*-webkit-transform: translate3d(0, 0, 0);
    -webkit-filter: blur(100px); 
    -moz-filter: blur(100px);
    -o-filter: blur(100px); 
    -ms-filter: blur(100px);
    filter: blur(100px);
    filter: url("/svg/filter.svg#blur");
    filter:progid:DXImageTransform.Microsoft.Blur(pixelradius=100);*/
  }
  .gallery_background image{
      width: 150%;
  }
  .hero__title {
    position: relative;
    text-align: center;
    font-size: 5em;
    color: white;
  }

.footer {
    margin-top: -1rem;}
  
@stop

@section('nothing')
.gallery {
  position: relative;
  width: 100%;
  padding: 2em 0;}
#galleryCanvas {
    position: absolute;
    display: block;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -10;}
.blur-ie {
    display: none;
    transform: scale(1.4);}
@stop

@section('content')
    <div class="gallery">
        <br/>
        <div class="row">
            <ul class="clearing-thumbs smal-up-2 medium-up-3 large-up-4 no-bullet">
                @foreach($posts as $post)
                    <li class="item-wrapper column">
                        <div class="img-wrapper text-center" itemid="{{ $post->url_q }}" itemscope itemtype="http://schema.org/Photograph">
                            <div itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
                                <a itemprop="contentUrl" class="thumbnail radius" data-toggle="modal-{{ $post->flickr_id }}" href="{{ $post->url_l }}">
                                    <img id="mainPhotoImage"
                                            filter="url(#blur)"
                                            alt="{{ $post->title }}"
                                            data-caption="{{ $post->title }}"
                                            width="{{ $post->width_q }}" 
                                            height="{{ $post->height_q }}" 
                                            src="{{ $post->url_q }}" itemprop="thumbnailUrl"/>
                                    <div class="title">
                                        <p class="vertical-center" itemprop="caption"><strong>{{ $post->title }}</strong></p>
                                        <p class="vertical-center" itemprop="dateTaken"><em>{{ $post->date_taken }}</em></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
        
        <div id="pagination-wrapper" class="row text-center">
            @include('site.flayout.page', ['results' => $posts])
        </div>
    </div>
    @foreach($posts as $post)
    <div class="full reveal text-center" id="modal-{{ $post->flickr_id }}" data-reveal data-reset-on-close="false" data-close-on-esc="true">
        <h2><strong>{{ $post->title }}</strong></h2>
        <div>
            <img class="thumbnail" height="1024" src="{{ asset('/images/loading.gif') }}" alt="{{ $post->title }}" />
        </div>
        <button class='close-button' data-close aria-label='Close reveal' type='button'>
            <span aria-hidden='true'>&times;</span>
        </button>
    </div>
    @endforeach
@stop

resources/views/site/portfolio/index.blade.php
@extends('site.' . config('app.layout') . '.default')

@section('title')
Portfolio :: @parent
@stop

@section('scripts')
<script src="{{ asset('/js/lightbox.js') }}"></script>
@stop

@section('added_jquery_script')
$('.clearing-thumbs').magnificPopup({
  delegate: 'a', // child items selector, by clicking on it popup will open
  type: 'image',
  gallery: {
      enabled: true,
      preload: [1,2],
  },
  image: {
      titleSrc: 'alt',
      verticalFit: true
  }
});
$('a.thumbnail').click(function(event){
    event.preventDefault();
});
@stop

@section('scripts_are_nothing')
$('#pictureModal').on('open.zf.reveal', function(event){
    //var topPos = ($(window).height() - $('#pictureModal').height()) / 2;
    //$('#pictureModal').css({'max-height':'1024px', 'margin-top':'0', 'top':topPos});
    $('#pictureModal, #pictureModal h2, #pictureModal div, #pictureModal div img').click(function(event){
        //$('#pictureModal button').trigger('click');
        $('#pictureModal').foundation('close');
    });
});
$('a.thumbnail').click(function(event){
    event.preventDefault();
    var title = $(this).children('img').attr('alt');
    var imgSrc = $(this).attr('href');
    $('#pictureModal #modal-pic-title').text(title);
    $('#pictureModal img').attr('height', 1024);
    $('#pictureModal img').attr('alt', title);
    $('#pictureModal img').attr('src', "{{ asset('/images/loading.gif') }}");
    $('#pictureModal img').attr('src', imgSrc);
});
@stop

@section('css')
<link rel="stylesheet" href="{{ asset('/css/lightbox.css') }}" />
@stop

@section('styles')
#pictureModal {
    height: 100%;
    max-height: 100%;
    width: 100% !important;
}
#loading_gif {
    position: absolute;
    left: 50%;
    top: 50%;
}
.img-wrapper {
    position: relative;
}

.img-wrapper a {
    /*display: block;*/
    position: relative;
    overflow: hidden;
}

.thumbnail:hover .title {
    opacity: 1;
}

.img-wrapper .title {
    position: absolute;
    overflow: hidden;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    background: #333;
    opacity: 0;
    padding: 1.5rem;
    color: #fff;
    background-color: rgba(0, 0, 0, 0.4);
}
.img-wrapper .title em {
    font-size: 0.8rem;
}
.item-wrapper:hover .img-wrapper .title {
    bottom: 8px;
}

.gallery {
  position: relative;
  width: 100%;
  overflow: hidden;
}
  .gallery_background {
    position: absolute;
    top: 0;
    left: -50%;
    width: 200%;
    height: 200%;
    z-index: -1;
    /*-webkit-transform: translate3d(0, 0, 0);
    -webkit-filter: blur(100px); 
    -moz-filter: blur(100px);
    -o-filter: blur(100px); 
    -ms-filter: blur(100px);
    filter: blur(100px);
    filter: url("/svg/filter.svg#blur");
    filter:progid:DXImageTransform.Microsoft.Blur(pixelradius=100);*/
  }
  .gallery_background image{
      width: 150%;
  }
  .hero__title {
    position: relative;
    text-align: center;
    font-size: 5em;
    color: white;
  }

.footer {
    margin-top: -1rem;}
  
@stop

@section('nothing')
.gallery {
  position: relative;
  width: 100%;
  padding: 2em 0;}
#galleryCanvas {
    position: absolute;
    display: block;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -10;}
.blur-ie {
    display: none;
    transform: scale(1.4);}
@stop

@section('content')
    <div class="gallery">
        <br/>
        <div class="row">
            <ul class="clearing-thumbs smal-up-2 medium-up-3 large-up-4 no-bullet" data-clearing>
                @foreach($posts as $post)
                    <li class="item-wrapper column">
                        <div class="img-wrapper text-center" itemid="{{ $post->url_q }}" itemscope itemtype="http://schema.org/Photograph">
                            <div itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
                                <a itemprop="contentUrl" class="thumbnail radius" href="{{ $post->url_l }}" alt="{{ $post->title }}">
                                    <img id="mainPhotoImage"
                                            alt="{{ $post->title }}"
                                            width="{{ $post->width_q }}" 
                                            height="{{ $post->height_q }}" 
                                            src="{{ $post->url_q }}"
                                            itemprop="thumbnailUrl"/>
                                    <div class="title">
                                        <p class="vertical-center" itemprop="caption"><strong>{{ $post->title }}</strong></p>
                                        <p class="vertical-center" itemprop="dateTaken"><em>{{ $post->date_taken }}</em></p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
        
        <div id="pagination-wrapper" class="row text-center">
            @include('site.flayout.page', ['results' => $posts])
        </div>
        <br/>
    </div>
    <div class="full reveal text-center" id="pictureModal" data-reveal data-reset-on-close="true" data-close-on-esc="true">
        <h2><strong id="modal-pic-title">Picture</strong></h2>
        <div>
            <img class="thumbnail" id="modalPic" height="1024" src="{{ asset('/images/loading.gif') }}" alt="Picture" />
        </div>
        <button class='close-button' data-close aria-label='Close reveal' type='button'>
            <span aria-hidden='true'>&times;</span>
        </button>
    </div>
@stop

resources/views/site/portfolio/indextwo.blade.php
@extends('site.' . config('app.layout') . '.default')

@section('title')
Portfolio :: @parent
@stop

@section('content')
    @if($posts->currentPage() == 1)
        <div class="callout primary">
            <div class="row">
            <h2>JPA Photography</h2>
            <p>Sometimes you learn more from your mistakes than you do from your masterpieces. Remember how
               free clouds are. They just lay around in the sky all day long. If you don't like it - change
               it. It's your world. We'll take a little bit of Van Dyke Brown. From all of us here, I want 
               to wish you happy painting and God bless, my friends. There's not a thing in the world wrong
               with washing your brush.</p>
            </div>
        </div>
    @endif

    <div class="gallery">
        <pre>
        {!! print_r($posts) !!}
        </pre>
    </div>

resources/views/site/portfolio/pword.blade.php
@extends('site.layouts.default')

@section('title')
Portfolio :: @parent
@stop

{{-- Content --}}
@section('content')
    Pword: {{ $cipher }}
@stop